spring:
  application:
    name: Spring Boot Fast Dev

  # Database settings
  datasource:
    url: jdbc:mysql://localhost:3306/db_fastdev?createDatabaseIfNotExist=true
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect